export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const GROCERYLIST_REQUEST = 'GROCERYLIST_REQUEST';
export const GROCERYLIST_SUCCESS = 'GROCERYLIST_SUCCESS';
export const GROCERYLIST_FAILURE = 'GROCERYLIST_FAILURE';

export const GROCERYLIST_CREATE_REQUEST = 'GROCERYLIST_CREATE_REQUEST';
export const GROCERYLIST_CREATE_SUCCESS = 'GROCERYLIST_CREATE_SUCCESS';
export const GROCERYLIST_CREATE_FAILURE = 'GROCERYLIST_CREATE_FAILURE';
export const CREATE_RECIPE_REQUEST = 'CREATE_RECIPE_REQUEST';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILURE = 'CREATE_RECIPE_FAILURE';

export const GROCERYLIST_INGREDIENT_SEARCH_REQUEST = 'GROCERYLIST_INGREDIENT_SEARCH_REQUEST';
export const GROCERYLIST_INGREDIENT_SEARCH_SUCCESS = 'GROCERYLIST_INGREDIENT_SEARCH_SUCCESS';
export const GROCERYLIST_INGREDIENT_SEARCH_FAILURE = 'GROCERYLIST_INGREDIENT_SEARCH_FAILURE';
export const GROCERYLIST_MEALPLAN_SEARCH_REQUEST = 'GROCERYLIST_MEALPLAN_SEARCH_REQUEST';
export const GROCERYLIST_MEALPLAN_SEARCH_SUCCESS = 'GROCERYLIST_MEALPLAN_SEARCH_SUCCESS';
export const GROCERYLIST_MEALPLAN_SEARCH_FAILURE = 'GROCERYLIST_MEALPLAN_SEARCH_FAILURE';

export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';

export const CREATE_INGREDIENT_REQUEST = 'CREATE_INGREDIENT_REQUEST';
export const CREATE_INGREDIENT_SUCCESS = 'CREATE_INGREDIENT_SUCCESS';
export const CREATE_INGREDIENT_FAILURE = 'CREATE_INGREDIENT_FAILURE';

export const MEALPLANS_REQUEST = 'MEALPLANS_REQUEST';
export const MEALPLANS_SUCCESS = 'MEALPLANS_SUCCESS';
export const MEALPLANS_FAILURE = 'MEALPLANS_FAILURE';

export const MEALPLAN_CREATE_REQUEST = "MEALPLAN_CREATE_REQUEST";
export const MEALPLAN_CREATE_SUCCESS = "MEALPLAN_CREATE_SUCCESS";
export const MEALPLAN_CREATE_FAILURE = "MEALPLAN_CREATE_FAILURE";

export const MEALPLAN_EDIT_REQUEST = "MEALPLAN_EDIT_REQUEST";
export const MEALPLAN_EDIT_SUCCESS = "MEALPLAN_EDIT_SUCCESS";
export const MEALPLAN_EDIT_FAILURE = "MEALPLAN_EDIT_FAILURE";

export const MEALPLAN_DELETE_REQUEST = "MEALPLAN_DELETE_REQUEST";
export const MEALPLAN_DELETE_SUCCESS = "MEALPLAN_DELETE_SUCCESS";
export const MEALPLAN_DELETE_FAILURE = "MEALPLAN_DELETE_FAILURE";

export const MEALPLAN_RECIPE_SEARCH_REQUEST = "MEALPLAN_RECIPE_SEARCH_REQUEST";
export const MEALPLAN_RECIPE_SEARCH_SUCCESS = "MEALPLAN_RECIPE_SEARCH_SUCCESS";
export const MEALPLAN_RECIPE_SEARCH_FAILURE = "MEALPLAN_RECIPE_SEARCH_FAILURE";

export const GET_RECIPES_REQUEST = 'GET_RECIPES_REQUEST';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_FAILURE = 'GET_RECIPES_FAILURE';
